Vagrant.configure("2") do |config|
  
  # Define the box to use
  config.vm.box = "gusztavvargadr/windows-server-core"
  config.vm.box_version = "2102.0.2402"
  
  # Provider-specific configurations
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2        
  end

  # Specify the hostname for your VM
  config.vm.hostname = "TenurITServer"

  # Enable bidirectional shared clipboard
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox", shared: true

  # Enable bidirectional drag'n'drop
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox", shared: true, mount_options: ["dmode=777", "fmode=666"]

  # Configure NAT network adapter
  config.vm.network "private_network", virtualbox__intnet: "TenurNAT"

  # Configure bridged adapter
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", auto_config: true
  
# Configure Brussels time zone
  config.vm.provision "shell", inline: "timedatectl set-timezone Europe/Brussels"

  # Configure Dutch Belgian keyboard layout
  config.vm.provision "shell", inline: "localectl set-keymap be-latin1"
end

